### ISSUE TITLE
Unexpected Output Shape

### ISSUE THREAD

**Issue by johnowhitaker** [lucidrains/perceiver-pytorch#10]
Running the example code from the readme, model(img) returns a tensor with shape (1, 1, 1000) rather than the expected (1, 1000):

![Screenshot from 2021-03-23 15-51-34](https://user-images.githubusercontent.com/6575163/112157280-be3c4e80-8bef-11eb-9d89-8e5823396a0f.png)

I've been having trouble getting the model to work with 1D input (audio) and before I spend too much time playing with it I wanted to see if this is the expected output shape or if there is something going wrong.

**Comment by lucidrains** [comment]
@johnowhitaker :bug: , should be fixed!

**Comment by nikhilbyte** [comment]
> Running the example code from the readme, model(img) returns a tensor with shape (1, 1, 1000) rather than the expected (1, 1000):
> 
> ![Screenshot from 2021-03-23 15-51-34](https://user-images.githubusercontent.com/6575163/112157280-be3c4e80-8bef-11eb-9d89-8e5823396a0f.png)
> 
> I've been having trouble getting the model to work with 1D input (audio) and before I spend too much time playing with it I wanted to see if this is the expected output shape or if there is something going wrong.

Hey John, were you able to get the code up for audio data?
