### ISSUE TITLE
Model implementation only allows latent transformers with one block

### ISSUE THREAD

**Issue by wzhang2022** [lucidrains/perceiver-pytorch#26]
The current implementation seems to only allow a single self-attention layer between the cross-attends. However, the original Perceiver paper describes a model where one can put a Transformer with an arbitrary number of blocks between cross attends. Their model on ImageNet used latent transformers with 6 blocks, with 8 cross-attends, giving a model that contains a total of 48 latent Transformer blocks.

**Comment by lucidrains** [comment]
@wzhang2022 sure! I can add that feature, maybe with an extra hyperparameter that describes the number of self attention blocks per cross attention?

**Comment by lucidrains** [comment]
@wzhang2022 ok, done in 0.2.0
