### ISSUE TITLE
Starting point of position encoding

### ISSUE THREAD

**Issue by ohwi** [lucidrains/perceiver-pytorch#29]
Hi. First of all, thank you for sharing the code.

As far as I understand, the code line below is evenly spacing the exponent.

https://github.com/lucidrains/perceiver-pytorch/blob/27a69f6c75939b0ebb1b0655695a54bb09289aca/perceiver_pytorch/perceiver_pytorch.py#L35

If I've understood the code correctly, I think 1 need to be 0 since log 1 = 0, as like `max_freq/2`.

**Comment by lucidrains** [comment]
@ohwi ohh, you may be right

**Comment by lucidrains** [comment]
@ohwi should be fixed in 0.2.1!
