### ISSUE TITLE
Missing channel dimension for input?

### ISSUE THREAD

**Issue by sooheon** [lucidrains/perceiver-pytorch#3]
In your example you have `torch.randn(1, 224 * 224)`, and the code assumes this 2d input. Isn't this lacking the `C` of `MxC : NxD` cross attention?

**Comment by lucidrains** [comment]
@sooheon  Hmm, that wasn't too clear to me in the paper 

I'm going to assume they just fourier encoded each channel separately and then concat them in the last dimension, for now https://github.com/lucidrains/perceiver-pytorch/commit/6ae733773d29cb29383f3ac7b45af8cb6bd2c0dc
