### ISSUE TITLE
Differences with Perceiver Preprint

### ISSUE THREAD

**Issue by fac2003** [lucidrains/perceiver-pytorch#31]
I think the implementation in this repo differs from the Perceiver preprint description in two significant ways:

1. The figure in the preprint and text indicate that the cross attention block is followed by a 'Latent Transformer'. The text indicates that the latent transformer has 6 blocks when training on ImageNet. This repo , to be fair, most re-implementations I have seen for Keras or JAx make the same mistake and use a single latent block, not a Latent Transformer with several blocks. 
2. The signature of the forward method in this implementation cannot support training with multi-modality inputs. Multi-modality is when you want to train with video, audio and image for instance as inputs to the same model. The signature does not support multi-modality because each modality has a different number of dimensions, and positional encoding must be applied to each modality independently. This is not possible when accepting a single x tensor as input to forward. 
I have implemented fixes for these two issues in this fork: https://github.com/fac2003/perceiver-multi-modality-pytorch

I tried contributing to this repo by starting to add tests, but the PR was rejected, so I won't bother to submit a PR for these fixes.

**Comment by lucidrains** [comment]
@fac2003 (1) the latent transformer is taken care of by this keyword argument https://github.com/lucidrains/perceiver-pytorch/blob/main/perceiver_pytorch/perceiver_pytorch.py#L149 - a transformer is just layers of self-attention, and by setting this to be greater than 1, you get the latent transformer

(2) what kind of modalities are you hoping to support? you can actually encode the data yourself and then just turn this flag to `False` https://github.com/lucidrains/perceiver-pytorch/blob/main/perceiver_pytorch/perceiver_pytorch.py#L148

I want to keep the library simple and avoid having different encodings for too many modalities. Images is enough for now
