### ISSUE TITLE
Fourier encoding should be for position coordinates instead of byte array

### ISSUE THREAD

**Issue by eridgd** [lucidrains/perceiver-pytorch#4]
The [`fourier_encode`](https://github.com/lucidrains/perceiver-pytorch/blob/6ae733773d29cb29383f3ac7b45af8cb6bd2c0dc/perceiver_pytorch/perceiver_pytorch.py#L28) function as implemented takes as input a byte array `x` and directly encodes it with sin/cos before concating with the input. 

As I understand the NeRF position encodings, they encode the x/y/etc. position coordinates, and not a transformation of the data itself. From the Perceiver paper:

> We parametrize the frequency encoding to take the values [sin(fkπxd), cos(fkπxd)], where the frequencies fk is the kth band of a bank of frequencies spaced log-linearly between 1 and µ/2... For example, by allowing the network to resolve the maximum frequency present in an input array, we can encourage it to learn to compare the values of bytes at any positions in the input array. xd is the value of the input position along the dth dimension (e.g. for images d = 2 and for video d = 3). xd takes values in [−1, 1] for each dimension. We concatenate the raw positional value xd to produce the final representation of position. This results in a positional encoding of size d(2K + 1).

NeRF position encoding examples:
* https://github.com/bmild/nerf/blob/20a91e764a28816ee2234fcadb73bd59a613a44c/run_nerf_helpers.py#L22
* https://github.com/ankurhanda/nerf2D

**Comment by lucidrains** [comment]
@eridgd Hi Evan again! I'm not too sure about this part, so I'm going to defer to what you said https://github.com/lucidrains/perceiver-pytorch/commit/37e2eb6650fb9f609f9aee39df5ed830f5550325 Let me know if that looks good to you!

**Comment by eridgd** [comment]
Thanks for the quick response! I'll give this a try and close the issue when verified.

**Comment by lucidrains** [comment]
ok cool! let us know

**Comment by lucidrains** [comment]
I have reports from a researcher friend that it is working for him, so closing
