### ISSUE TITLE
Normalization happens before layers instead of afterwards

### ISSUE THREAD

**Issue by SurrealEverything** [lucidrains/perceiver-pytorch#42]
Why is PreNorm used? Shouldn't normalization happen after the residual connections on each layer, like this:
```
PostNorm(_, Residual(FeedForward(...
```
?

**Comment by lucidrains** [comment]
@SurrealEverything where in the paper do you see that it is post-normalization?

**Comment by SurrealEverything** [comment]
You are right. The paper uses PreNorm. Sorry about this. Didn't know it's a thing.

**Comment by lucidrains** [comment]
no problem!
