### ISSUE TITLE
Not using the classification head in Perceiver

### ISSUE THREAD

**Issue by gegallego** [lucidrains/perceiver-pytorch#47]
Hi @lucidrains, thank you for your great job!

I'd like to use the Perceiver (not PerceiverIO) without the classification head (average and projection). Do you think we could add an option to avoid using it? I can do a PR if you want.

Thanks!

**Comment by lucidrains** [comment]
sure! do you mean return this? https://github.com/lucidrains/perceiver-pytorch/blob/main/perceiver_pytorch/perceiver_pytorch.py#L247

**Comment by gegallego** [comment]
No, just before that line, I'd like to avoid the `mean`.

**Comment by lucidrains** [comment]
@gegallego ok! let me know if https://github.com/lucidrains/perceiver-pytorch/commit/b33aced4e1b266aeb1383e03ab63f0a9951f9126 suits your need

**Comment by gegallego** [comment]
Yes, perfect, thank you very much!
