### ISSUE TITLE
Fourier encoding is not similar to the paper

### ISSUE THREAD

**Issue by cheneeheng** [lucidrains/perceiver-pytorch#5]
First of all, thanks for sharing the code !

I have a follow up question to #4.

In the paper, the authors mentioned about _[sin(f_k*π*x_d), cos(f_k*π*x_d)], where f_k is a bank of frequencies spaced log-linearly between 1 and µ/2._ Can you maybe point out how you came to the 1/2**i scaling in the code ?

https://github.com/lucidrains/perceiver-pytorch/blob/6ae733773d29cb29383f3ac7b45af8cb6bd2c0dc/perceiver_pytorch/perceiver_pytorch.py#L28-L35

Thanks!

**Comment by lucidrains** [comment]
@cheneeheng ohh yes, you are right, I transcribed that from NERF but didn't modify it to be like what the paper said

what do you think is a reasonable default value for the hyperparameter mu?

**Comment by lucidrains** [comment]
@cheneeheng https://github.com/lucidrains/perceiver-pytorch/pull/6/files could you possibly review this code to see if it makes sense?

**Comment by cheneeheng** [comment]
> @cheneeheng ohh yes, you are right, I transcribed that from NERF but didn't modify it to be like what the paper said
> 
> what do you think is a reasonable default value for the hyperparameter mu?

The paper mentioned : 

_For example, by allowing the network to resolve the maximum frequency present in an input array, we can encourage it to learn to compare the values of bytes at any positions in the input array._

Which sounds like it is dynamically chosen based on input data. Would need to be confirmed from the authors though or run some experiments. For now I think setting to 10 should be ok.

As for the band number K:

The paper is lightly confusing on this part. Page 6 mentioned about _and positional encodings generated with 64 bands_ and Page 8 mentioned _higher maximum frequency on ModelNet40 (256) than for image data_. I suspect the former to be correct and the latter to be a typo since the paper mentioned in Appendices that the band number is used to increase sampling "denseness".

> @cheneeheng https://github.com/lucidrains/perceiver-pytorch/pull/6/files could you possibly review this code to see if it makes sense?

Done.

**Comment by lucidrains** [comment]
ok, merged the PR! thanks for reviewing the code and the issue :)
