### ISSUE TITLE
Positional encoding frequency bands should be linearly spaced

### ISSUE THREAD

**Issue by djl11** [lucidrains/perceiver-pytorch#52]
A small bug, but as alluded to in this [comment](https://github.com/lucidrains/perceiver-pytorch/issues/51#issuecomment-927149945) by @marcdumon, it seems as though the frequency bands are indeed [spaced linearly](https://github.com/deepmind/deepmind-research/blob/master/perceiver/position_encoding.py#L53) in the official JAX implementation.

**Comment by lucidrains** [comment]
@djl11 thanks Daniel, i think you are correct :pray: let me know if this version looks correct to you https://github.com/lucidrains/perceiver-pytorch/releases/tag/0.7.4

**Comment by djl11** [comment]
Looks good!
