### ISSUE TITLE
PerceiverAR?

### ISSUE THREAD

**Issue by siddk** [lucidrains/perceiver-pytorch#60]
Hey @lucidrains - love this repo, and still trying to wrap my head around the various difference between Perceiver architectures; how hard would it be to extend PerceiverIO to PerceiverAR; what fundamentally needs to change?

**Comment by lucidrains** [comment]
@siddk oh hey Sid, good to hear from you. a number of things actually - i think the consensus at Eleuther was that perceiver AR is not very promising. i don't have any plans on building it, if that is what you mean

**Comment by siddk** [comment]
Hey Phil - no sorry, wasn't intending for you to build it! Just wanted to get your thoughts on usability of your current code for the AR model (if it makes sense). 

If it isn't too much trouble, could you tag me/point me to the discussion on the viability of the model?

**Comment by siddk** [comment]
Thanks so much! Found the discussion... makes a good point, maybe I'm overthinking things 😅. Thanks so much for the kind response @lucidrains!

**Comment by lucidrains** [comment]
@siddk sounds good, good luck with your studies / research :)
