### ISSUE TITLE
Perceiver IO wrong ouput dims (fully connected layer (nn.Linear) not applied)

### ISSUE THREAD

**Issue by VladPetk** [lucidrains/perceiver-pytorch#66]
Hi everyone, 

I am trying to train the Perceiver IO model for sequence to sequence. I have the following parameters:
```
model = PerceiverIO(
    dim=4,               # Input dimension

    queries_dim=4,       # Query dimension

    logits_dim=4,       # Logits dimension

    depth=6,                    # Model depth

    num_latents=512,     # Number of latents

    latent_dim=256,      # Latent dimension

    cross_heads=4,              # Number of cross-attention heads

    latent_heads=8,             # Number of latent self-attention heads

    cross_dim_head=64,          # Dimensions per cross-attention head

    latent_dim_head=64,         # Dimensions per latent self-attention head

    weight_tie_layers=False,     # Whether to tie weights between layers

    seq_dropout_prob=0.1,       # Sequence dropout probability (adjust as needed)
)
```

For some reason, the output of my model is in shape [batch_size, 512, 256] instead of [batch_size, 512, 4]. I checked the code for the PerceiverIO and there is this line (what the model actually returns):
` self.to_logits = nn.Linear(queries_dim, logits_dim) if exists(logits_dim) else nn.Identity()`

So it should go with `nn.Linear` since I have defined logits_dim, but it seems to be going for `nn.Identity` nevertheless. 

Any ideas why? Much appreciated!

**Comment by lucidrains** [comment]
@VladPetk ohh it is because you need to supply the `queries` that attention pool over the latents

try `model(input, queries = torch.randn(7, 4))`

**Comment by lucidrains** [comment]
@VladPetk you can see the full example at https://github.com/lucidrains/perceiver-pytorch/blob/main/perceiver_pytorch/perceiver_io.py#L261

**Comment by VladPetk** [comment]
@lucidrains Thanks a bunch, makes sense!
