### ISSUE TITLE
x = self.latents + self.pos_emb

### ISSUE THREAD

**Issue by galchinsky** [lucidrains/perceiver-pytorch#8]
```
self.latents = nn.Parameter(torch.randn(num_latents, latent_dim))
self.pos_emb = nn.Parameter(torch.randn(num_latents, latent_dim))
...
x = self.latents + self.pos_emb
```

I'm not very familiar with pytorch, but does this make sense? I mean, what's intended when 2 trainable weight matrices are simply summed and that's that's the only place where both `latents` and `pos_emb` appear. It looks like it can be replaced with only one matrix.

**Comment by lucidrains** [comment]
@galchinsky Hi Dmitry! it goes back to a conversation here https://github.com/lucidrains/perceiver-pytorch/issues/1 you are right, perhaps it is redundant

**Comment by lucidrains** [comment]
@galchinsky maybe you can try running an experiment on your problem and let us know :)

**Comment by galchinsky** [comment]
@lucidrains aah, sorry, I did look through the closed issues but I didn't check your patch in #1 and it seemed non related. I think either your initial code is correct or (less likely) `pos_emb` is added after each iteration of the loop. The current implementation is indeed redundant because each update step the weights are changed equally

**Comment by lucidrains** [comment]
@galchinsky i'll go back to the way it was before
